//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasks
{
    using System;
	using System.Configuration;
	using System.Data.Entity;
	using System.Data.Entity.Core.EntityClient;
	using System.Data.Entity.Infrastructure;
	using System.Data.SqlClient;

	public partial class JOBSEntities : DbContext
    {
        public JOBSEntities()
            : base("name=JOBSEntities")
        {
        }

        public JOBSEntities(string path) : base(path)
        {
        }

        //public string GenerateConnectionStringEntity(string connEntity)
        //{

        //    // add a reference to System.Configuration
        //    var entityCnxStringBuilder = new EntityConnectionStringBuilder
        //        (System.Configuration.ConfigurationManager
        //            .ConnectionStrings["JOBSEntities"].ConnectionString);

        //    // init the sqlbuilder with the full EF connectionstring cargo
        //    var sqlCnxStringBuilder = new SqlConnectionStringBuilder
        //        (entityCnxStringBuilder.ProviderConnectionString);

        //    // only populate parameters with values if added
        //    if (!string.IsNullOrEmpty(initialCatalog))
        //        sqlCnxStringBuilder.InitialCatalog = initialCatalog;
        //    if (!string.IsNullOrEmpty(dataSource))
        //        sqlCnxStringBuilder.DataSource = dataSource;
        //    if (!string.IsNullOrEmpty(userId))
        //        sqlCnxStringBuilder.UserID = userId;
        //    if (!string.IsNullOrEmpty(password))
        //        sqlCnxStringBuilder.Password = password;

        //    // set the integrated security status
        //    sqlCnxStringBuilder.IntegratedSecurity = integratedSecuity;

        //    // now flip the properties that were changed
        //    source.Connection.ConnectionString
        //        = sqlCnxStringBuilder.ConnectionString;
        //}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Current_Music> Current_Music { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<DatesJob> DatesJobs { get; set; }
        public virtual DbSet<DatesSubJob> DatesSubJobs { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Music> Musics { get; set; }
        public virtual DbSet<SubJob> SubJobs { get; set; }
        public virtual DbSet<Tv_Movies> Tv_Movies { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
    }
}
