//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tv_Movies
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public System.DateTime Date_Added { get; set; }
        public int Year { get; set; }
        public bool Type { get; set; }
        public Nullable<int> Episode_Count { get; set; }
    }
}
