//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasks__MVP_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Current_Music
    {
        public long Job_ID { get; set; }
        public long Count { get; set; }
        public string Album { get; set; }
        public long ID { get; set; }
    }
}
