//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasks__MVP_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.DatesJobs = new HashSet<DatesJob>();
        }
    
        public long Job_ID { get; set; }
        public string Name { get; set; }
        public long Category { get; set; }
        public Nullable<System.DateTime> Last_Finished { get; set; }
        public System.DateTime Date_Added { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public long Frequency { get; set; }
        public long Importance { get; set; }
        public bool Completed { get; set; }
        public long Job_Type { get; set; }
        public long Est_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatesJob> DatesJobs { get; set; }
        public virtual SubJob SubJob { get; set; }

		public override string ToString()
		{
            return $"{Name.Trim()}  - {Category} : {Last_Finished.Value.ToShortDateString()}";
		}
	}
}
