//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasks__MVP_
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubJob()
        {
            this.DatesSubJobs = new HashSet<DatesSubJob>();
        }
    
        public long Job_ID { get; set; }
        public long Count { get; set; }
        public double Per_Day { get; set; }
        public long Total_Done { get; set; }
        public Nullable<long> Page_Number { get; set; }
        public Nullable<long> Base_Count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatesSubJob> DatesSubJobs { get; set; }
        public virtual Job Job { get; set; }
    }
}
